### ISSUE TITLE
Homebridge

### ISSUE THREAD

**Issue by NicosHere** [roslovets/SP110E-HASS#1]
Hi,

I've got a SP110E Controller and I've been looking around to see if there is any way to connect it to homebridge.

I'm on a rpi 3 with bluetooth and it doesn't look like anyone has made any plugin for this.

I've got minimal coding experience and I'm not sure how to apply what I've seen in your repositories to my homebridge.

Would you be able to help with this?

**Comment by roslovets** [comment]
Hi, check out [SP110E](https://github.com/roslovets/SP110E) repository, especially:

- Asynchronous API [reference](https://github.com/roslovets/SP110E/blob/main/docs/controller.md)
- [Examples](https://github.com/roslovets/SP110E/tree/main/examples)
