### ISSUE TITLE
HA does not connect to SP110E any logs?

### ISSUE THREAD

**Issue by SmartHomeFanatic** [roslovets/SP110E-HASS#2]
Hey there!
Much appreciate that you created this plugin! Always wanted to integrate my SP110E into HA since I got it.

Is there any kind of log that I can have a look in why my HA instance isn't able to connect to the SP110E?
Is the MAC address that the 'LED Hue' app shows while connecting to the SP110E the one that I can use in my config?

Thanks for your help!

**Comment by roslovets** [comment]
> Is the MAC address that the 'LED Hue' app shows while connecting to the SP110E the one that I can use in my config?

Yes, this is it. First of all close Led Hue app and reconnect your lamp to the power source to close bluetooth connection.

If it will not help, enable strict mode in configuration (strict: true). After that you shoud see error details in Server Journal (/config/logs)
