### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by leafnight** [roslovets/SP110E-HASS#3]
I just came into contact with this, and I just installed a part of the program. What should a novice do to start this project from scratch, how to configure the environment, and compile and burn

**Comment by roslovets** [comment]
Just follow the [installation guide](https://github.com/roslovets/SP110E-HASS#installation). I do it every time for testing.
If you want to supress errors in PyCharm during development use Poetry to install dependencies.

**Comment by danielbrunt57** [comment]
> how to configure the environment, and compile and burn

Compile and burn?  Compile/burn what??
