### ISSUE TITLE
Requirements not found again

### ISSUE THREAD

**Issue by th3d00d** [roslovets/SP110E-HASS#5]
Hello,
after the last Issue with sp110e 1.4.0 has been fixed, it worked great, until a few days ago, when I noticed the device stopped responding. When I checked earlier today, I noticed I was getting the Message "**Platform error light.sp110e - Requirements for sp110e not found: ['sp110e==1.4.1'].**" again :/

**Comment by roslovets** [comment]
Hi, what is your HASS version?

**Comment by th3d00d** [comment]
Hello, I am running the following on a Raspberry Pi 4:

Home Assistant 2022.9.0b3
Supervisor 2022.08.6
Operating System 9.0.rc1
Frontend 20220902.0 - latest

**Comment by roslovets** [comment]
Fixed in [v1.0.2](https://github.com/roslovets/SP110E-HASS/releases/tag/v1.0.2). Tested in HASS 2022.8.7, HACS 1.26.2. Thanks
